### ISSUE TITLE
Pytanie dotyczonce bezpieczenstwa chemsdok

### ISSUE THREAD

**Issue by nvx0** [mesiik/cheems.crack#2]
Uplod som bezpiecne? Uzytkownicy bezpiecni? Eto fix when????? Pzdrowaiam z serwerowni contabo

**Comment by nvx0** [comment]
rowniez pozdrawiam tryb bomby atomowej wlonczony + bomba rurowa zostala wyslana do gdyni!!!!!!!!!!! 🥺🥺🥺🎉🎉🤷‍♂️🤷‍♂️❌💀💀🫥🫥🫤🤷‍♂️🙂🙂🙂

**Comment by adasiek193** [comment]
XDDDDDDDDDDD
